### ISSUE TITLE
Move to Babel/Babelify

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/r3dm.com#20]
Removes the need to track compiled files.

**Comment by morenoh149** [comment]
Where does this fit? in lieu of reactify browserify transform?

**Comment by BerkeleyTrue** [comment]
There are three points to this.
- Replace reactify with babelify
- Add bebel require hook to server.js https://babeljs.io/docs/using-babel/#require-hook
- remove compiled files from repo tracking and modify requires paths to look for .jsx files were applicable.
