### ISSUE TITLE
Add info@r3dm.com

### ISSUE THREAD

**Issue by morenoh149** [r3dm/r3dm.com#24]
Our connect form is great. But many visitors expect a simple email somewhere on the site.

**Comment by morenoh149** [comment]
@BerkeleyTrue what would be the best way to achieve this? the csstransition groups in the connect form are making it difficult for me to add an anchor tag. How is the height of the connect form determined? it seems to be calculated at runtime as any css rules I make get overridden.

**Comment by BerkeleyTrue** [comment]
Yes they are. Add a new section underneath or add the link in the footer.
