### ISSUE TITLE
Add lenore's extra pics (in a feature branch)

### ISSUE THREAD

**Issue by morenoh149** [r3dm/r3dm.com#45]
Either to the work section using nuka. Or direct visitor to a new page.

**Comment by BerkeleyTrue** [comment]
I think this is overkill.

**Comment by morenoh149** [comment]
"I would use just some of the mockups. I like the ones mocked up into photos best, but it's easier to see the screens on the stand alones. I would put the one with all 3, then no more than one mockup for each screen" - lenore

**Comment by BerkeleyTrue** [comment]
The way it looks now is great. The other images should be used in a blog post. The work section isn't meant to be a gallery. Changing it now breaks the flow that is there.

**Comment by BerkeleyTrue** [comment]
How about creating a feature branch and see how it would look like.
