### ISSUE TITLE
Add thundercats to work section

### ISSUE THREAD

**Issue by morenoh149** [r3dm/r3dm.com#53]
Use microsoft and facebook logos. Appeal to authority.

**Comment by BerkeleyTrue** [comment]
Why would we use their logos?

**Comment by morenoh149** [comment]
What do you envision here? You could take the lead on this section if you'd like.

I was thinking their logos because I originally thought of using the flux logo and the RxJS logo but then realized they probably don't mean anything to a non tech person. But everyone knows facebook and microsoft.

**Comment by BerkeleyTrue** [comment]
We can't use any of those logos.

**Comment by morenoh149** [comment]
http://www.microsoft.com/en-us/legal/IntellectualProperty/Trademarks/Usage/Logo.aspx cant use logo
