### ISSUE TITLE
recent changes to navbar results in broken UI

### ISSUE THREAD

**Issue by BerkeleyTrue** [r3dm/r3dm.com#59]
Link underscore incorrectly placed.
![r3dm](https://cloud.githubusercontent.com/assets/6775919/7740532/dedbc216-ff27-11e4-9a95-eda7a7068009.png)

Larger font breaks spacing
![r3dm](https://cloud.githubusercontent.com/assets/6775919/7740538/f60257fc-ff27-11e4-8e36-103388321ee6.png)

**Comment by BerkeleyTrue** [comment]
a tag for link doesn't take up whole bar resulting in weird hover styling
![r3dm](https://cloud.githubusercontent.com/assets/6775919/7740630/59d6bcae-ff29-11e4-863b-6a837d2bfbbb.png)

**Comment by morenoh149** [comment]
I see 
![screenshot 2015-05-20 19 52 10](https://cloud.githubusercontent.com/assets/587438/7740681/21bfc6b6-ff2a-11e4-8977-e388105b358b.png) on latest thundercats

**Comment by BerkeleyTrue** [comment]
This might be an issue with my version of Chrome. FF seems to render fine on my end.

**Comment by BerkeleyTrue** [comment]
Definitely something wrong with my Chrome. Tried another chromium browser and it renders awesomely!
