### ISSUE TITLE
swap temp photo

### ISSUE THREAD

**Issue by morenoh149** [r3dm/r3dm.com#61]
Current photo has `slideshare` in upper left corner. Replace with new photo provided by lenore.

**Comment by BerkeleyTrue** [comment]
Which photo?

**Comment by morenoh149** [comment]
![app-screens-perspective-mockup_1024](https://cloud.githubusercontent.com/assets/587438/7825653/53f0c7d6-03c4-11e5-837c-f89613014263.png)

**Comment by morenoh149** [comment]
![app-screens-perspective-mockup](https://cloud.githubusercontent.com/assets/587438/7825678/b3434fb0-03c4-11e5-9bd0-391c0f0b030a.png)

**Comment by BerkeleyTrue** [comment]
Oh most def
